language: java
addons:
  sonarcloud:
    organization: "wtekiela"
    token:
      secure: "HIyfkrDQQwHRgvFLeCzrnPmnJny05RXNtUYZtm6/48TYkeRju/fMMzQE0mY0vOVyJVRsssyQHS+f/vJX/RF3pSHAlbUTQ3Pl90/Q/TfZdWzGnPZh28avoa+HGBATV0tiKdvYgtDI67ywarEZZdfTXrzT/zEkc3g7sz1vd8MfM/s="
install:
  - travis_retry ./gradlew assemble -x signArchives
script:
  - travis_retry ./gradlew check sonarqube